name: Deploy

on:
  push:
    branches: ['main']

env:
  AWS_REGION: ap-northeast-1
  ECS_SERVICE: eibunmemo-service-51-28
  ECS_CLUSTER: eibunmemo-rails-cluster
  ECS_TASK_DEFINITION: eibunmemo-task-51

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'

      - name: Install dependencies
        run: bundle install

      - name: Setup database
        run: |
          bundle exec rails db:drop
          bundle exec rails db:create
          bundle exec rails db:schema:load
        env:
          RAILS_ENV: test
          DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Rubocop
        run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}

  rails_build_and_push:
    needs: test
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Rails image
        run: |
          docker build -t ${{ secrets.ECR_RAILS_REPOSITORY }}:latest -f prd/Dockerfile .

      - name: Tag and push Rails image to Amazon ECR
        run: |
          docker tag ${{ secrets.ECR_RAILS_REPOSITORY }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_RAILS_REPOSITORY }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_RAILS_REPOSITORY }}:latest

  nginx_build_and_push:
    needs: rails_build_and_push
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Nginx image
        run: |
          docker build -t ${{ secrets.ECR_NGINX_REPOSITORY }}:latest -f prd/nginx/Dockerfile .

      - name: Tag and push Nginx image to Amazon ECR
        run: |
          docker tag ${{ secrets.ECR_NGINX_REPOSITORY }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_NGINX_REPOSITORY }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_NGINX_REPOSITORY }}:latest

  deploy:
    needs: nginx_build_and_push
    runs-on: ubuntu-20.04

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download the current ECS task definition
        id: download-task-def
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query "taskDefinition" --output json > task-definition.json

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
